### PR TITLE
Group Tasks

### LINKED ISSUE #1: [1pt] Create Item class
* Create Item class in a separate .rb file.

* All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.

### LINKED ISSUE #2: [1pt] Add and implement all methods visible in the diagram
Methods:

1) can_be_archived?() in the Item class
* should return true if published_date is older than 10 years
* otherwise, it should return false
2) move_to_archive() in the Item class
* should reuse can_be_archived?() method
* should change the archived property to true if the result of the can_be_archived?() method is true
* should do nothing if the result of the * can_be_archived?() method is false

### LINKED ISSUE #3: [1pt] Create main.rb & Implement startup actions
Create a main.rb file that will serve as your console app entry-point.

* Create Item class in a separate .rb file.

* All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.

### LINKED ISSUE #4: [1pt] Implement startup actions
* Create Item class in a separate .rb file.
* All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.

### PR DESCRIPTION
**Pull request by melaniesigrid**
Thank you for reviewing this PR. Here, team members @fabgrel10 @gabyse1 and I completed the following:

- Create Item class in a separate .rb file.
- All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.
- Add all methods visible in the diagram.
- Implement methods:
  - can_be_archived?() in the Item class
    - should return true if published_date is older than 10 years
    - otherwise, it should return false
- move_to_archive() in the Item class
  - should reuse can_be_archived?() method
  - should change the archived property to true if the result of the can_be_archived?() method is true
  - should do nothing if the result of the can_be_archived?() method is false
- Create a main.rb file that will serve as your console app entry-point.
- Implement startup actions:
  - Present the user with a list of options to perform.
  - Let users choose an option.
  - If needed, ask for parameters for the option.
  - Have a way to quit the app.

Your comments will be appreciated! ⭐

### CODE REVIEW

File: lib/item.rb [hunk 1]
```diff
@@ -0,0 +1,19 @@
+require 'date'
+
```
Comment (ghost) [inline lib/item.rb:2]: Properties for the 1-to-many relationships are missing, implement them, please.

File: main.rb [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+  puts '7 - Add a book'
+  puts '8 - Add a music album'
+  puts '9 - Add a game'
+  puts '10 - Exit'
+end
+
+def main
+  app = App.new
+  option = 0
+  while option != 13
```
Comment (ghost) [inline main.rb]: I only see 10 different options, please correct that.

**Review by ghost — CHANGES_REQUESTED** [review]
Hello team, excellent so far!

This milestone is almost done. There are few error that you still need to correct. Please go ahead and fix them.

**Review by ghost — APPROVED** [review]
Excellent team! You solve the previous pointed issues!
